language: android
android:
  components:
    - build-tools-21.1.0
    - android-21
    - sys-img-x86-android-19
before_script:
    - echo no | android create avd --force -n test -t android-19 --abi x86
    - emulator -avd test -no-skin -no-audio -no-window & 
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
